-- ========================================================
-- OBE Study Tracker - Supabase SQL Schema
-- Paste this entire script into your Supabase SQL Editor
-- ========================================================

-- 1. Create tables
-- Each table connects to auth.users to keep user data private.
-- 'on delete cascade' ensures that if a user deletes their account,
-- or deletes a semester, all related subjects and marks are also deleted automatically.

CREATE TABLE public.semesters (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null
);

CREATE TABLE public.subjects (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    semester_id bigint not null references public.semesters(id) on delete cascade,
    code text not null,
    name text not null
);

CREATE TABLE public.ct_marks (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    subject_id bigint not null references public.subjects(id) on delete cascade,
    ct_no integer not null,
    mark numeric not null
);

CREATE TABLE public.other_marks (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    subject_id bigint not null references public.subjects(id) on delete cascade,
    attendance numeric default 0,
    assignment numeric default 0,
    -- A subject should only have one record for attendance/assignment marks
    unique(subject_id)
);


-- ========================================================
-- 2. Enable Row Level Security (RLS)
-- This is critical! It ensures that a user can ONLY see
-- and edit their own semesters, subjects, and marks.
-- ========================================================

ALTER TABLE public.semesters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ct_marks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.other_marks ENABLE ROW LEVEL SECURITY;


-- ========================================================
-- 3. Create RLS Policies
-- We allow users to perform ALL actions (SELECT, INSERT, UPDATE, DELETE)
-- but ONLY if the user_id on the row matches their logged-in auth.uid()
-- ========================================================

-- Policies for Semesters
CREATE POLICY "Users can manage their own semesters" 
    ON public.semesters
    FOR ALL 
    USING (auth.uid() = user_id);

-- Policies for Subjects
CREATE POLICY "Users can manage their own subjects" 
    ON public.subjects
    FOR ALL 
    USING (auth.uid() = user_id);

-- Policies for CT Marks
CREATE POLICY "Users can manage their own ct_marks" 
    ON public.ct_marks
    FOR ALL 
    USING (auth.uid() = user_id);

-- Policies for Other Marks
CREATE POLICY "Users can manage their own other_marks" 
    ON public.other_marks
    FOR ALL 
    USING (auth.uid() = user_id);
